const pass = require('pass');
const exp = require('exp');
const path= require('path');
var mongoose = require('mongoose');
const bodyPar = require('body-parser');
const cors = require('cors');
const users = require('./routers/users');
const config = require('./config/database');
const app = express();
